### ISSUE TITLE
The contract has already been initialized

### ISSUE THREAD

**Issue by GaloisField2718** [near-daos/sputnik-dao-contract#172]
At the 5th step (Initialize Factory) 

Scheduling a call: marseille.testnet.new()
Doing account.functionCall()
Receipt: 5QYfUzQaNisH7EWV4pynDMS7zpxKjWDybA24ZBzoE5Bq
        Failure [marseille.testnet]: Error: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: The contract has already been initialized"}}
ServerTransactionError: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: The contract has already been initialized"}}
    at Object.parseResultError (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:160:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async scheduleFunctionCall (/usr/local/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'FunctionCallError',
  context: undefined,
  index: 0,
  kind: {
    ExecutionError: 'Smart contract panicked: The contract has already been initialized'
  },
  transaction_outcome: {
    block_hash: '6tYUZ93nt2a7g1NVWy5Hw4MPyE6iU72NZytSAZEY1C8e',
    id: 'GhazSZ7pH2AAT4wgcYSXF39uwUTNTMArCHeDuohfNjCZ',
    outcome: {
      executor_id: 'marseille.testnet',
      gas_burnt: 2427932179670,
      logs: [],
      metadata: [Object],
      receipt_ids: [Array],
      status: [Object],
      tokens_burnt: '242793217967000000000'
    },
    proof: [ [Object], [Object], [Object], [Object] ]
  }
}

How can I erase previous contract to create a new one, and initialize it with the procedure specified in README file

**Comment by GaloisField2718** [comment]
I have not neardev file. 
I tried to erase sputnikdaofactory2.wasm and download again. Apparently it works.

Thank you, and thank you again to solve my other issue !
